import time
print("MY CHRISTMAS LIST\n")

#import time
import datetime

now = time.time()

birthday = time.strptime("25 Dec 19", "%d %b %y")
how_long_to_wait = time.mktime(birthday) - now

print("Today is {}.".format(time.asctime()))
time.sleep(3)

print("Christmas is on {} ".format(time.asctime(birthday)))
time.sleep(3)

print("That's {} to go ...".format(
    datetime.timedelta(seconds=how_long_to_wait)))
time.sleep(3)

print(" ")
time.sleep(1)
print("1. THINGS HAPPENING")
time.sleep(1)
print("* NOBODY BEING ANOYING *")
time.sleep(5)
print("* Get a dog PLEEEEEEEEEAAAAAAAAASE *")
time.sleep(0.3)
print("* NO ANGRY, SHOUTING OR ANOYED ALIVE THINGS *")
time.sleep(0.3)
print("* IceScating PLEEEEEEEEEAAAAAAAAASE *")
time.sleep(4)
print(" ")
print("2. BOOKS")
time.sleep(3)
print("- WARRIORS - THE NEW PROPHECY; THE NEXT BOOK")
time.sleep(2)
print("- Aru Shah and the tree of wishes(Roshani Chokshi)")
print("- Something I haven't heard of that I'll like (I want to try some thing new)")
time.sleep(1)
print("- A sherlock holmes book")
time.sleep(1)
print("- Pocket eyewitness mammals (toppings)")
time.sleep(2)
print("- ")
time.sleep(2)
print(" ")
time.sleep(5)
print("3. SPORTY THINGS")
print("* Astro-turf boots")
print("* short-sleeved Larkhall football top")
print(" ")
time.sleep(5)
print("4. OTHER")
print("- save the world - in fortnite")
print("- subbuteo (football card game)(water-stones)")
print("- red moon-ball(Hyper bouncing ball)(water-stones)")
print("- Fancy box thing (the works)")
print("- more laptop stickers:)")
print(" ")
time.sleep(5)
print("5. FOOD")
print("* Breakfast: Toast (or buns)")
print("* lunch: Pasta and pesto or (brown)tortia wrap(with sweetcorn ,tuna and cheese))") 
print("* Tea: Pasta and Pesto(if I have pasta and pesto for lunch Pizza instead)")
print("* Cake: Lemon drizzle or chocolate cake")
print("* sweets to take into school")
print(" ")
time.sleep(5)
print("6. DVDs")
print("- more Hiccup and toothless")
print("- and more hiccup and toothless")
print("- Avengers Endgame")
print("- Captain Marvel")
print(" ")
time.sleep(5)
print("7, 8, 9 & 10. ANYTHING ELSE YOU CAN THINK OF")